### ISSUE TITLE
Hi~!

### ISSUE THREAD

**Issue by WaltzofLeave** [qiangbo1222/HierDiff#1]
Hello qiangbo1222,

I hope this message finds you well.

Firstly, I must commend your impressive and inspiring work which I've been closely following recently. The depth of your research and the finesse of your implementation have left me intrigued and deeply appreciative.

As a fellow enthusiast in this field, I've been trying to understand the intricacies of your work and how I can integrate similar approaches into my projects. I believe that by exploring your code and methodologies, I will be able to grasp the concepts more comprehensively.

With that said, I **was wondering if you would be comfortable sharing your code with me?**  **My email address is berylacevedo5630@gmail.com** I understand the amount of effort and dedication that goes into writing code, and the privacy concerns that may come with sharing it. So, I promise to respect and uphold the integrity of your work at all times. I'm only seeking to learn and expand my knowledge base.

Your positive response would be immensely appreciated. Thank you for considering my request, and I look forward to potentially learning from your work.

Best regards.

**Comment by qiangbo1222** [comment]
Thanks for your interest! I am still cleaning my code for the public release. The code will be uploaded to this repo by the end of this month if nothing comes up unexpectedly (I promise to upload before the opening of icml conference). You can keep following this repository.
