### ISSUE TITLE
Problem regarding some missing files

### ISSUE THREAD

**Issue by DongkiKim95** [qiangbo1222/HierDiff#3]
Hello!

Thanks for your insightful work! I appreciate that your work impresses me with a new type of generative model!

Currently, I am working on training the fine-grained generative model network with `train_refine_pl.py` and `train_edge_denoise_pl.py`

However, it seems that  `dataset/atom_embed_dict.pkl` and `dataset/size_dict.pkl` do not exist.

Could you provide how to make those files or share them with us?

Best.

**Comment by qiangbo1222** [comment]
Thanks！
Sorry for the inconvenience of applying our code. The two pickled files have been uploaded.

**Comment by DongkiKim95** [comment]
Thanks for your fast response!

Now it is running normally, so I close this issue.
