### ISSUE TITLE
About Evaluation Metrics

### ISSUE THREAD

**Issue by Gloria-LIU** [qiangbo1222/HierDiff#4]
Hi Bo,

Thank you again for the amazing work!
I'd like to know the difference metrics you use for ∆LogP and ∆MW calculations. 
Also, can you provide the MCF calculation criteria list? Thanks!

**Comment by qiangbo1222** [comment]
For ∆LogP and ∆MW, there is no difference between the calculations. We simply use the absolute value of the difference of the mean from the sampled molecules and the molecules from the test set.

The MCF criteria can be found in the popular benchmark MOSES(https://github.com/molecularsets/moses). They used the name filter for this metric.
