### ISSUE TITLE
crossdock split file for pocket based generation

### ISSUE THREAD

**Issue by Gloria-LIU** [qiangbo1222/HierDiff#7]
Hi,

Could you provide "data/split_by_name.pt" for the "crossdock_cond" setting?
Thank you!

**Comment by ghost** [comment]
Hello, I encountered the same problem. Can you provide the "data/split_by_name.pt" file? Thank you very much.

**Comment by Gloria-LIU** [comment]
I think it's the same one used in [TargetDiff](https://github.com/guanjq/targetdiff/tree/142f1eb7178480d435fe0b8cb95a99beb48997c7?tab=readme-ov-file), [AR](https://arxiv.org/abs/2203.10446) and [Pocket2Mol](https://arxiv.org/abs/2205.07249), and it's available [here](https://drive.google.com/drive/folders/1j21cc7-97TedKh_El5E34yI8o5ckI7eK).

**Comment by ghost** [comment]
Thank you.
