### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by xzliu6** [qiangbo1222/HierDiff#8]
Hello, thank you very much for the code, I understand that you trained this model with 4 A100-80G and it took two days, thank you very much for your work, but I don't have such training conditions, can you please provide the pretrained model, I will be grateful if you can provide it.

**Comment by QYFfly** [comment]
I can't find pretrained checkpoint in repo. Can you release it?

**Comment by qiangbo1222** [comment]
Thank you for your interest in our work! You can decrease the batch size to better fit your GPU during training. I apologize for any inconvenience, but I'm currently a bit busy. I will release the checkpoint as soon as I have some free time.
